name: CI Files should be terminated by newline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Detect CRLF line endings
        run: find . -type f | xargs file | grep CRLF
