name: Files should be terminated by newline

on:
  push
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set git to use LF
        run: |
          git grep -Il $'\r'
          git config --global core.autocrlf false
          git config --global core.eol lf
